# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: Check build and run tests
on: workflow_dispatch
jobs:
  check-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: >-
          ./gradlew --console=plain --stacktrace --scan
          build
env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx5g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  GPG_key_id: ${{ secrets.GPG_KEY_ID }}
  GPG_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_private_password: ${{ secrets.GPG_PRIVATE_PASSWORD }}
